spring.application.name=backend
spring.application.name=Netlab-BulletHellShootEmUp-BE-SaidAbdullahSamy 
spring.datasource.url=jdbc:postgresql://ep-hidden-shadow-b3nhwbkg-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_VJLk4MfW8htC&sslmode=require&channelBinding=require
